### PR TITLE
Implemented Highcharts

### PR DESCRIPTION
**Pull request by feldsam**
Replaced old graph library by modern JS graphs powered by Highcharts

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by dfranco** [comment]
Thanks for the efforts to improve the graphs.
Is HighChart license compatible (technically and philosophically) with current project license ?

**Comment by feldsam** [comment]
Hello, I dont know, but there is no highchart codebase included in this pull request. I just linking src JS/CSS to CDN.

**Comment by dfranco** [comment]
Hi,
Even you don't use the source locally by using their CDN, their license still apply.

I have check the license of HightChart (see links below)
https://shop.highsoft.com/highcharts
https://shop.highsoft.com/faq#Non-Commercial-0
Looks to be a problem as it restrict to a limited type of usage.

In the past, I was looking for an open source charting library to replace PHPLot and found these one.

- C3 (MIT license) https://github.com/c3js/c3
- Ploty (MIT license) https://plot.ly/highcharts-alternative/

What do you think ?

Regards

**Comment by dfranco** [comment]
Hello,
I'm sorry but the license of HighCharts is not compatible with Bacula-Web license.
But don't worry, I'll keep your work on this and try to implement the libs mentioned in my previous comment.
Best regards

**Pull request closed without merging**
