### PR TITLE
Changed Job Filters To GET Requests. Links in Dashboard 

### PR DESCRIPTION
**Pull request by atze234**
Related to http://bugs.bacula-web.org/view.php?id=195

### CODE REVIEW

**Comment by atze234** [comment]
included http://bugs.bacula-web.org/view.php?id=244

**Comment by dfranco** [comment]
Hi @atze234,

Thanks for this merge request.
I see a lot of changes, can you explain a bit more the purpose of these changes ?

By the way, you've cloned the wrong branch (master instead of develop).
http://docs.bacula-web.org/en/latest/04_contribute/development.html#guidance-for-developpers

I'll get back to you once I've reviewed your changes.

Cheers

**Comment by atze234** [comment]
Hi @dfranco ,
sorry for the wrong branch. 
I wanted to separate those 2 Commits, but did that wrong i think, did not branch i think -.- Not using github often :(

The purpose of the Changes of my first commit:
Change POST to GET Requests in the Search Forms (Jobs firstofall, so that i can hit the "Back" Button in Browser. Second, with GET Requests for the Search Filter we can Link things easily. So i created some Links (Failed Jobs/Succeeded Jobs on the Dashboard)  

In my second Commit i've added an extra Sort Order on the Volumes Page, so that i can Sort by Inchanger and Name for example. The Volumes View is quite hard to read with >1000 Volumes. And i added the inchanger sort keyword at all here. Maybe little too much copy&paste in the Volumes View Class, but ... i think its ok.

Best Regards

**Comment by dfranco** [comment]
Hi @atze234 ,

For the first purpose, there's already a bug report open
http://bugs.bacula-web.org/view.php?id=195

For the second one, I've added a note the bug report.
Let me know what you think.

Anyway, I'll merge your code (at least some part) into the right branch.
It might not be in 8.0.0 stable release but the next one I guess.

Kind regards

**Comment by dfranco** [comment]
Hi @atze234 ,
I'll try to integrate some of your code in next 8.4.0 release.
Thanks for your contribution

**Comment by dfranco** [comment]
The first issue is fixed, and you can filter volumes with "in changer" checkbox.
I'm closing this PR.

Thanks a lot for your contribution

**Pull request closed without merging**
