### PR TITLE
Added responsive design to whole application

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristián Feldsam feldsam@gmail.com

### CODE REVIEW

**Comment by feldsam** [comment]
Hello, I tested it on my mobile phone and as well on desktop browser too. Thought 2days testing I fixes bugs and improved details.

This is final version for this pull request.

You should install latest version with this patch aside and test it by yourself.

**Comment by dfranco** [comment]
I'll have a try on my side and merge this PR if everything is fine.

Thanks a million !!!

**Comment by feldsam** [comment]
Hi, any news with testing?

**Comment by dfranco** [comment]
Hi, not yet.
Too busy with other projects.
But I'm going to merge all PR over the week-end and more bugfix / features.
So a new release is coming soon ;)
Regards

**Comment by dfranco** [comment]
Merged locally and checking your branch.
I'll get back to you quickly.

**Comment by feldsam** [comment]
what is in browser console?

**Comment by dfranco** [comment]
no errors in console

**Comment by feldsam** [comment]
so would you post some screnshot or make site accessible public?

**Comment by dfranco** [comment]
It was a Smarty cache issue, now I can see the accordion and what you've done with other commits.

**Comment by feldsam** [comment]
great

**Comment by dfranco** [comment]
PR merged, thanks for the great work.

**Pull request merged**
