### PR TITLE
Implemented File Listing within a Job

### PR DESCRIPTION
**Pull request by unimigliore**
Implemented a new Model, View and Template to list Files contained in each Job.

### CODE REVIEW

**Comment by dfranco** [comment]
Hi @unimigliore,

Thanks for this pull request, I'll review it soon.

P.S: I see you've cloned master branch instead of develop.
http://docs.bacula-web.org/en/latest/04_contribute/development.html

**Comment by unimigliore** [comment]
Hello @dfranco,
yes, i've cloned master branch. 
If it is an error, i will clone develop branch and i will copy there the code.

Bye

**Comment by dfranco** [comment]
Hi @unimigliore ,

no problem, I'll figure out how to merge your changes into develop branch.

Kind regards

**Comment by dfranco** [comment]
Feature request created

https://bugs.bacula-web.org/view.php?id=289

**Comment by dfranco** [comment]
Renamed HistoryFiles to JobFiles PHP classes and variables.

**Comment by dfranco** [comment]
Hi @unimigliore ,

Your PR have been merged into develop branch and the feature is now available in version 8.3.0.

Thanks again for your contribution.

Davide

**Pull request closed without merging**
