### PR TITLE
Client week size

### PR DESCRIPTION
**Pull request by sakrow**
0000197 feature in http://bugs.bacula-web.org/

Get more info from size of clients backup and the backup size in the week days.

### CODE REVIEW

**Comment by dfranco** [comment]
Hi,
I've merged your PR (it was painful).
Thanks for the new features, they will be available in next version (7.4.0)
Best regards

**Comment by sakrow** [comment]
@dfranco Was painful for why? Code? Or number of changes?
Was my first contribution to one open repository.

**Comment by dfranco** [comment]
@sakrow : because I had to fix merge conflict and not easy to fix it when there's code indentation changes (not your fault).
@wanderleihuttel ok good to know, let me check first

**Comment by dfranco** [comment]
I had to revert this pull request due to many problems within the code such as

- usage of JobTDate field in Job table (why don't stick with starttime as other functions)
- using postgreSQL doesn't work as you're using FROM_UNIXTIME (known only by MySQL as far as I know)
- Widget "Best backup day" should not be in the catalog statistics
- Functions created in client.model.php should be in job.model.php (mainly related to Job and not client)
- etc.
I'll will include these nice features for sure, but I need to understand and cleanup the code first.
Thanks

**Pull request merged**
