### PR TITLE
Added Scheduled time on Jobs report

### PR DESCRIPTION
**Pull request by sgargel**
This is adding "Scheduled Time" to Jobs report.

### CODE REVIEW

**Comment by dfranco** [comment]
Very good addition, thanks for this.
But testing your branch on my test server, I see that the Job history table became very large.
People with small screen resolution might have problems to see all the informations.
I might need to move the filter/options from the right to somewhere else.

**Comment by sgargel** [comment]
Thanks, One solution may be a function for selecting which columns to display but I'm not so skilled...

Inviato da Yahoo Mail su Android 
 
  Il ven, 10 feb, 2017 alle 17:19, Davide Franco<notifications@github.com> ha scritto:   
Very good addition, thanks for this.
But testing your branch on my test server, I see that the Job history table became very large.
People with small screen resolution might have problems to see all the informations.
I might need to move the filter/options from the right to somewhere else.

**Comment by dfranco** [comment]
Good idea, thanks

**Comment by wanderleihuttel** [comment]
Hello 
Is necessary include "Scheduled Time" in translations file.

Best Regards
Wanderlei

**Comment by dfranco** [comment]
Hi,
I'll fix the template and update the messages.po for next release.

Thanks again
Davide

**Pull request merged**
