### PR TITLE
 Support filtering by pool on job listing page

### PR DESCRIPTION
**Pull request by ctrochalakis**
A small patch adding filtering jobs by pool.

### CODE REVIEW

**Comment by dfranco** [comment]
Hello,
Thank you for the PR.
I've tested it and found several PHP errors in Apache log
PHP Notice:  Undefined index: job_status_filter in ....
I'll try to fix it and pull it in master when it's clean.

Best regards
Davide

**Comment by feldsam** [comment]
Hi @ctrochalakis, would you update your branch from actual master and resolve conflicts and fix php notices? Would be fine have this merged.

**Comment by dfranco** [comment]
Hello @ctrochalakis , do you mind creating a new pull request (or even several) without conflicts please ?
Check documentation before -> http://bacula-web.org/Development.html
Thanks

**Comment by dfranco** [comment]
Hi @ctrochalakis,
I've implemented this feature by myself based on the code you've comited in this pull request.
Thanks a million for the great idea

**Pull request closed without merging**
